var ifConfig =

{
  "orderForm": {
    "academicLevel": [
      "General",
      "Specialized"
    ],
    "typeOfPaper": [
      "Creative writing",
      "Essay (any type)",
      "Research paper",
      "Presentation or speech",
      "Book/movie review",
      "Term paper",
      "Coursework",
      "Research proposal",
      "Dissertation",
      "Thesis",
      "Business plan",
      "Case study",
      "Admission essay",
      "Article review",
      "Annotated bibliography",
      "Argumentative essays",
      "Critical thinking",
      "Biographies",
      "Thesis/Dissertation abstract",
      "Dissertation chapter - Introduction",
      "Dissertation chapter - Literature review",
      "Dissertation chapter - Methodology",
      "Dissertation chapter - Results",
      "Dissertation chapter - Discussion",
      "Dissertation chapter - Conclusion",
      "Thesis/Dissertation proposal",
      "Thesis/Dissertation chapter",
      "Capstone project",
      "Other (enter below)"
    ],
    "subjectOfDiscipline": [
      "Art (Fine arts, Performing arts)",
      "Classic English Literature",
      "Composition",
      "English 101",
      "Film & Theater studies",
      "History",
      "Linguistics",
      "Literature",
      "Music",
      "Philosophy",
      "Poetry",
      "Religious studies",
      "Shakespeare",
      "Anthropology",
      "Cultural and Ethnic Studies",
      "Economics",
      "Ethics",
      "Political science",
      "Psychology",
      "Social Work and Human Services",
      "Sociology",
      "Tourism",
      "Urban Studies",
      "Women's & gender studies",
      "Accounting",
      "Business Studies",
      "Finance",
      "Human Resources Management (HRM)",
      "International Relations",
      "Logistics",
      "Management",
      "Marketing",
      "Public Relations (PR)",
      "Astronomy (and other Space Sciences)",
      "Biology (and other Life Sciences)",
      "Chemistry",
      "Ecology",
      "Geography",
      "Geology (and other Earth Sciences)",
      "Physics",
      "Zoology",
      "Computer science",
      "Mathematics",
      "Statistics",
      "Agriculture",
      "Application Letters",
      "Architecture, Building and Planning",
      "Aviation",
      "Civil Engineering",
      "Communications",
      "Criminal Justice",
      "Criminal law",
      "Education",
      "Engineering",
      "Environmental studies and Forestry",
      "Family and consumer science",
      "Health Care",
      "International Trade",
      "IT, Web",
      "Law",
      "Leadership Studies",
      "Medical Sciences (Anatomy, Physiology, Pharmacology etc.)",
      "Medicine",
      "Nursing",
      "Nutrition/Dietary",
      "Public Administration",
      "Sports",
      "Technology",
      "Other (enter below)"
    ]
  }
};

if (typeof window === 'undefined')
  exports.ifConfig = ifConfig;
